### ISSUE TITLE
有关仿真环境的问题：加载环境时没有出现人

### ISSUE THREAD

**Issue by xduxiaohai** [SYSU-STAR/CICRSIM#1]
![image](https://github.com/SYSU-STAR/CICRSIM/assets/53559220/d2186e78-c06c-46e0-9f2b-c3b33dd9e258)
如上图所示，系统是Ubuntu20.04 ros-noetic

**Comment by xduxiaohai** [comment]
而且是在断网的情况下

**Comment by thinkerhui** [comment]
我的Ubuntu18.04也有这样的情况，不知道是不是这个仿真对硬件的要求比较高，感觉运行的时候挺占内存的

**Comment by RoboticsZhuang** [comment]
> 而且是在断网的情况下

你有把模型文件放入 .gazebo/models 中吗

**Comment by xduxiaohai** [comment]
> > 而且是在断网的情况下
> 
> 你有把模型文件放入 .gazebo/models 中吗

你好，现在能够启动gazebol了，但是显示界面有一点问题，如下图所示：

![image](https://github.com/SYSU-STAR/CICRSIM/assets/53559220/f6df40ff-924a-4803-b787-5e250a8cb613)
![image](https://github.com/SYSU-STAR/CICRSIM/assets/53559220/4462f36d-ade3-47f5-9fda-f2989a925e6c)
![image](https://github.com/SYSU-STAR/CICRSIM/assets/53559220/517de8dd-e37c-429f-a5ae-54dc619a72dd)

即墙壁和障碍物都是透明的
