### ISSUE TITLE
【已解决】catkin_make时候出现Apriltag_info.h找不到

### ISSUE THREAD

**Issue by act18l** [SYSU-STAR/CICRSIM#3]
catkin_make时候出现Apriltag_info.h找不到
请问有人知道是什么原因吗？
系统是ROS Melodic(Ubuntu18.04)。
![error](https://github.com/SYSU-STAR/CICRSIM/assets/17793885/c434d487-5c36-4507-bb5d-4c87219a7e31)

**Comment by xduxiaohai** [comment]
> catkin_make时候出现Apriltag_info.h找不到 请问有人知道是什么原因吗？ 系统是ROS Melodic(Ubuntu18.04)。 ![error](https://user-images.githubusercontent.com/17793885/243190964-c434d487-5c36-4507-bb5d-4c87219a7e31.png)
我第一次编译也遇到这个问题，但是当我我重新catkin_make编译时，没有遇到报错，顺利编译完成

**Comment by sysu19351064** [comment]
我的环境是Ubuntu20.04，参考了readme中第5部分Q&A，其中的第三个办法，将uav_simulation包中的cmakelist.txt中第五行的 
 set(CMAKE_CXX_FLAGS "-std=c++11") ，改成了 set(CMAKE_CXX_FLAGS "-std=c++17")，成功编译了。

**Comment by act18l** [comment]
> 我的环境是Ubuntu20.04，参考了readme中第5部分Q&A，其中的第三个办法，将uav_simulation包中的cmakelist.txt中第五行的 set(CMAKE_CXX_FLAGS "-std=c++11") ，改成了 set(CMAKE_CXX_FLAGS "-std=c++17")，成功编译了。

我还是不行，等会试试20.04的

**Comment by act18l** [comment]
我自己的解决方法：把整个cicr2023_simulator文件夹移开，catkin_make，移回去再catkin_make
