### ISSUE TITLE
仿真物理环境中模型出现位置偏移

### ISSUE THREAD

**Issue by Ohmmm3** [SYSU-STAR/CICRSIM#4]
- Ubuntu 20.04
- ROS Noetic
- Gazebo 11

直接通过 `gazebo CICR2023.world` 打开仿真世界是正常的，如下图
![1b62a268a230c899a3be11ec6fef502](https://github.com/SYSU-STAR/CICRSIM/assets/60022568/53e39cba-3dc2-4619-8fe5-8ceb08eaa6ed)

但是如果通过 launch 文件打开 `roslaunch uav_simulation env_simulation.launch` ，就会出现位置偏移问题如下图
![c5fa45934c3033f4766ccb0286950d3](https://github.com/SYSU-STAR/CICRSIM/assets/60022568/eff95440-1517-47b7-b0a5-f3c6ff602dbb)

尝试了更换 Gazebo 9，可以解决上述问题，但是打开之后就不会生成无人机。猜测是因为 ROS Noetic 对应的 ros-noetic-gazebo-ros 之类的包的版本好像默认是 Gazebo 11，所以不知道如何解决这个问题。

**Comment by sysu19351064** [comment]
我尝试过两个版本，Ubuntu18.04和Ubuntu20.04，gazebo版本都是11，也出现了模型偏移。我猜测是world文件中最外层围墙模型的位置发生了偏移，因此我尝试修改了CICR2023.world文件。

在CICR2023.world中line94的位置，我把<poseframe>中的参数全部修改为零，即
`<pose frame=''>0 0 0 0 -0 0</pose>`

无需编译后启动程序，可以发现偏移解决了，但是无人机的停机坪标志模型出现在了正中央，我不确定是否因为修改了上面的参数导致的。

**Comment by Ohmmm3** [comment]
十分感谢您抽出时间解答，问题解决了！
（关于您所说的停机坪标志位置出现在正中央的问题，我按照您说的方法同样在 `.world` 文件里面进行手动修改，可以比较粗暴地解决这个问题，即 `<link name='startflag'>` 下的位姿设置为 `<pose frame=''>8.5 4 0.115 0 -0 0</pose>`）
