### ISSUE TITLE
控制节点打开了之后报错

### ISSUE THREAD

**Issue by bytehandsome** [SYSU-STAR/CICRSIM#8]
使用系统ubuntu18.04,有确保模型被解压缩到~/.gazebo/models目录下面，报错如下：
![图片](https://github.com/SYSU-STAR/CICRSIM/assets/49219172/fff6df96-e41e-4e7e-9980-f233bd1877d8)
![图片](https://github.com/SYSU-STAR/CICRSIM/assets/49219172/d81d9118-c82d-4649-83b2-ff986f5e152c)

**Comment by sysu19351064** [comment]
针对第二张图的模型解压缩，可以把原来的.gazebo/models文件夹全部删除，重新执行新的脚本如下：
`#!/bin/bash
sudo unzip ./models.zip -d ~/.gazebo
sudo cp -r ./apriltag ~/.gazebo/models/apriltag
sudo cp -r ./files ~/YOUR_WORKSPACE_PATH
sudo cp -r ./start_simulation.sh ~/YOUR_WORKSPACE_PATH`

**Comment by bytehandsome** [comment]
我按照您的指示，显示把.gazebo/models文件夹全部删除，然后复制了最新的sim_env.sh执行，倒是解决了人加载不出来的问题，但是上面控制节点依旧是上面的结果，另外附上同时出现的报错和更新后的.gazebo/models文件夹
![图片](https://github.com/SYSU-STAR/CICRSIM/assets/49219172/97e14d4e-caec-471d-9508-6a98fa1441ca)
![图片](https://github.com/SYSU-STAR/CICRSIM/assets/49219172/9f01d99d-58f4-493a-aba7-2fb4bbb33c2b)


> 针对第二张图的模型解压缩，可以把原来的.gazebo/models文件夹全部删除，下载项目里最新的sim_env.sh，重新执行一次。

**Comment by sysu19351064** [comment]
先确认一下现在是否有下载最新的代码

**Comment by bytehandsome** [comment]
> 先确认一下现在是否有下载最新的代码
非常感谢，下载最新的代码后控制节点可以使用～
